# Generated by Django 3.1.1 on 2020-09-25 03:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('galleriesappp', '0004_auto_20200921_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='actress',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='albums',
            name='actress',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='galleriesappp.actress'),
        ),
    ]
