# Generated by Django 3.1 on 2020-09-28 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galleriesappp', '0006_carousel_carouselitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carouselitem',
            options={'ordering': ['weight']},
        ),
        migrations.RemoveField(
            model_name='carouselitem',
            name='carousel',
        ),
    ]
