# Generated by Django 3.1 on 2020-09-28 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleriesappp', '0007_auto_20200928_2052'),
    ]

    operations = [
        migrations.CreateModel(
            name='carouselslide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image1', models.ImageField(upload_to='media/')),
            ],
        ),
        migrations.DeleteModel(
            name='Carousel',
        ),
        migrations.DeleteModel(
            name='CarouselItem',
        ),
    ]
