# Generated by Django 3.1.1 on 2020-09-29 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleriesappp', '0008_auto_20200928_2059'),
    ]

    operations = [
        migrations.CreateModel(
            name='carouselslideX',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image2', models.ImageField(upload_to='media/')),
            ],
        ),
    ]
